/** This small loader stays inert after whole-plugin removal; it never regenerates deleted files. */
import type { Context } from '@deepseek-ai/cordis'
import { access, readFile, mkdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { withFileLock } from '@deepseek-ai/dsh-atomic-write'
import { recoverModuleTransaction } from './module-transaction.ts'
import { atomicJson, compareReleaseVersions, validateManifest, verifyArtifact, type ArtifactRoots } from './module-files.ts'
import { ModuleManager } from './module-manager.ts'
import type * as Runtime from './runtime-host.ts'
import { dshHomePath } from '@deepseek-ai/dsh-home-paths'
import { eraseRemovedPlugin } from './module-cleanup.ts'
import { acquireModuleLease, recoverModuleLock } from './module-lease.ts'
import { createRouteGuard } from './http-trust.ts'

/**
 * runtime/ is generated by the packaging step and is not tracked, so a source
 * install that never ran it ships no payload. Check it before anything else so
 * the loader reports the remedy instead of a bare ENOENT on the manifest path,
 * and name the source-address case plus the uninstall-then-reinstall step that
 * actually clears it (a same-version reinstall is refused while the broken copy
 * is still listed as installed).
 */
async function assertInstalledPayload(runtime: string): Promise<void> {
  try { await access(resolve(runtime, 'manifest.json')) }
  catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
    throw new Error('dsh-damage-pulse: the installed payload is incomplete: runtime/manifest.json is '
      + 'missing, so the plugin cannot start. The most common cause is installing from a source address '
      + '(a repository URL, a `github:` spec, a source archive, or an unpacked source tree that was never '
      + 'built), which ships no payload because only the packaging step generates it; a damaged or partly '
      + 'extracted install looks the same. Install the published package for the profile you actually use: '
      + '`dsh plugin --profile <profile> add dsh-damage-pulse`, or the .tgz from the GitHub Release. If the '
      + 'target profile still lists a broken copy of the same version, uninstall it first and install '
      + 'again; unbuilt source can build the payload before mounting it.')
  }
}

/** Prefer a persisted module release after an in-place update, but let a newer package take over. */
export function selectBootManifest(packageManifest: unknown, stateManifest: unknown) {
  const packaged = validateManifest(packageManifest)
  if (stateManifest === undefined) return packaged
  const persisted = validateManifest(stateManifest)
  return compareReleaseVersions(persisted.version, packaged.version) >= 0 ? persisted : packaged
}

export async function bootModules(ctx: Context, pluginRoot: string, clientRoot: string): Promise<void> {
  const runtime = resolve(pluginRoot, 'runtime')
  await assertInstalledPayload(runtime)
  // Package managers replace node_modules during upgrades. Keep tombstones and
  // the transaction journal in the profile, outside the installed payload.
  const stateFile = resolve(pluginRoot, '..', '..', '.dsh-damage-pulse', 'module-state.json')
  const legacyStateFile = resolve(runtime, 'state.json')
  const roots: ArtifactRoots = { host: resolve(runtime, 'host'), assets: resolve(runtime, 'assets'), client: clientRoot }
  await mkdir(dirname(stateFile), { recursive: true })
  const releaseLease = await acquireModuleLease(stateFile)
  ctx.effect(() => releaseLease, 'token-monitor: exclusive installed runtime')
  await recoverModuleLock(stateFile)
  const { manifest, removed } = await withFileLock(stateFile, async () => {
    try { await readFile(stateFile, 'utf8') }
    catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
      // In-place installations can migrate the old package-local state.
      // A legacy transaction needs recovery with its original package first.
      try {
        await readFile(legacyStateFile + '.transaction.json', 'utf8')
        throw new Error('LEGACY_MODULE_RECOVERY_REQUIRED')
      } catch (journalError) {
        if ((journalError as NodeJS.ErrnoException).code !== 'ENOENT') throw journalError
      }
      try { await atomicJson(stateFile, JSON.parse(await readFile(legacyStateFile, 'utf8'))) }
      catch (legacyError) { if ((legacyError as NodeJS.ErrnoException).code !== 'ENOENT') throw legacyError }
    }
    await recoverModuleTransaction(stateFile, roots)
    let state: { manifest?: unknown; wholePlugin?: unknown } | undefined
    try { state = JSON.parse(await readFile(stateFile, 'utf8')) }
    catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error }
    const manifest = selectBootManifest(JSON.parse(await readFile(resolve(runtime, 'manifest.json'), 'utf8')), state?.manifest)
    if (!state?.wholePlugin) for (const file of manifest.core) await verifyArtifact(roots, file)
    return { manifest, removed: !!state?.wholePlugin }
  })
  if (removed) {
    // Teardown and erasure precede deletion. A restart only retries remaining locked payload files.
    const manager = await ModuleManager.open(manifest, stateFile, roots, {
      stop: async () => {}, start: async () => {}, stopCore: async () => {}, startCore: async () => {},
      // The whole-plugin record is authoritative; partial feature cleanup is subsumed.
      eraseData: async (id, selection) => { if (id === 'plugin' && selection) await eraseRemovedPlugin(ctx, dshHomePath('data', 'dsh-token-monitor'), selection) },
    })
    // The host still discovers the package's static client entry. Expose only
    // the durable tombstone so that entry stays dormant after a restart.
    ctx.inject(['webServer', 'connection'], web => {
      const guard = createRouteGuard(web)
      web.effect(() => web.webServer.register({
        kind: 'exact', path: '/api/token-monitor/modules', handler: (req, res) => {
          if (!guard(req, res)) return
          if (req.method !== 'GET') { res.writeHead(405); res.end(); return }
          res.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' })
          res.end(JSON.stringify(manager.snapshot()))
        },
      }), 'token-monitor: removed plugin snapshot')
    })
    return
  }
  const entry: typeof Runtime = await import(pathToFileURL(resolve(roots.host, 'manager.mjs')).href + `?v=${manifest.version}`)
  await entry.apply(ctx, { roots, stateFile, manifest })
}
